#ifndef HEATERCONTROLLER_GLOBAL_H
#define HEATERCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HEATERCONTROLLER_LIBRARY)
#  define HEATERCONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HEATERCONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HEATERCONTROLLER_GLOBAL_H
